import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
    id: {
        // Nav & Common
        appName: 'Manajemen Barang',
        appSubtitle: 'Sistem Inventaris',
        home: 'Beranda',
        dashboard: 'Dashboard',
        products: 'Produk',
        categories: 'Kategori',
        suppliers: 'Pemasok',
        stockInOut: 'Stok Masuk / Keluar',
        batch: 'Batch Inventaris',
        reports: 'Laporan Data',
        logout: 'Logout',
        logoutConfirmTitle: 'Konfirmasi Logout',
        logoutConfirmText: 'Anda akan keluar dari sistem inventaris.',
        cancel: 'Batal',
        save: 'Simpan',
        saving: 'Menyimpan...',
        saved: 'Disimpan',
        delete: 'Hapus',
        edit: 'Ubah',
        actions: 'Aksi',
        success: 'Berhasil',
        error: 'Error',
        warning: 'Peringatan',
        searchPlaceholder: 'Cari produk, kategori, atau kode...',
        searchNav: 'Cari...',

        // Header
        notifications: 'Notifikasi',
        inventoryNotifications: 'Notifikasi Inventaris',
        markAsRead: 'Tandai dibaca',
        noNotifications: 'Tidak ada notifikasi saat ini.',
        toggleTheme: 'Ganti Tema',
        myProfile: 'Profil Saya',
        settings: 'Pengaturan',

        // Settings Page
        settingsTitle: 'Pengaturan',
        settingsSubtitle: 'Kelola preferensi dan pengaturan sistem sesuai kebutuhan Anda.',
        tabAppearance: 'Tampilan',
        tabAppearanceSub: 'Tema dan tampilan antarmuka',
        tabWarehouse: 'Gudang & Scanner',
        tabWarehouseSub: 'Scanner QR, batch, dan kode gudang',
        tabNotifications: 'Notifikasi',
        tabNotificationsSub: 'Pengaturan notifikasi sistem',
        tabSecurity: 'Keamanan',
        tabSecuritySub: 'Ubah password dan keamanan akun',
        tabDataManagement: 'Manajemen Data & Cadangan',
        tabDataManagementSub: 'Cadangkan database dan bersihkan cache aplikasi',
        tabAbout: 'Tentang Sistem',
        tabAboutSub: 'Informasi versi dan aplikasi',

        sectionAppearance: 'Tampilan',
        sectionAppearanceDesc: 'Atur tema dan tampilan aplikasi sesuai preferensi Anda.',
        labelTheme: 'Tema',
        themeLight: 'Light',
        themeLightDesc: 'Tampilan terang',
        themeDark: 'Dark',
        themeDarkDesc: 'Tampilan gelap',
        themeSystem: 'System',
        themeSystemDesc: 'Mengikuti sistem',
        darkModeActive: 'Mode Gelap Aktif',
        lightModeActive: 'Mode Terang Aktif',
        darkPreviewDesc: 'Tampilan lebih nyaman di mata saat kondisi cahaya rendah.',
        lightPreviewDesc: 'Tampilan bersih dengan kontras tinggi untuk siang hari.',

        sectionLanguage: 'Bahasa & Lokalisasi',
        sectionLanguageDesc: 'Atur bahasa dan format data yang digunakan dalam aplikasi.',
        labelLanguage: 'Bahasa',
        langIndonesian: 'Bahasa Indonesia',
        langEnglish: 'English (US)',

        sectionOther: 'Pengaturan Lainnya',
        sectionOtherDesc: 'Sesuaikan beberapa pengaturan tambahan.',
        toggleAutoRefresh: 'Refresh otomatis dashboard',
        toggleAutoRefreshDesc: 'Pembaruan data berkala otomatis',
        toggleShowStock: 'Tampilkan jumlah stok',
        toggleShowStockDesc: 'Tampilkan jumlah stok di kartu produk',
        refreshInterval: 'Interval Waktu Auto-Refresh',
        interval1m: '1 Menit (Pergerakan Cepat)',
        interval3m: '3 Menit',
        interval5m: '5 Menit (Standar)',
        interval10m: '10 Menit',
        autoRefreshActiveBadge: 'Auto-Refresh Aktif',
        autoRefreshOffBadge: 'Auto-Refresh Nonaktif',
        lastUpdatedLabel: 'Terakhir diperbarui',
        refreshNowBtn: 'Segarkan Sekarang',
        refreshingStatus: 'Memperbarui data...',
        stockHidden: 'Disembunyikan',

        displayPreferences: 'Format Data & Tampilan Tabel',
        displayPreferencesDesc: 'Sesuaikan kerapatan baris, urutan default data, dan jumlah baris tabel per halaman.',
        paginationLimit: 'Jumlah Baris per Halaman (Tabel)',
        rows10: '10 Baris per Halaman',
        rows25: '25 Baris per Halaman',
        rows50: '50 Baris per Halaman',
        rows100: '100 Baris per Halaman',
        tableDensity: 'Kerapatan Baris Tabel',
        densityComfortable: 'Normal / Nyaman (Standar)',
        densityCompact: 'Ringkas / Padat (Lebih Banyak Data)',
        defaultSort: 'Urutan Default Data Tabel',
        sortNewest: 'Terbaru Ditambahkan',
        sortLowestStock: 'Stok Menipis Dahulu (Prioritas Restock)',
        sortHighestStock: 'Stok Terbanyak Dahulu',
        sortNameAsc: 'Nama Produk (A - Z)',
        dateFormat: 'Format Tanggal Transaksi',
        dateFormatId: 'Standar Indonesia (DD/MM/YYYY)',
        dateFormatIso: 'Standar ISO / Logistik (YYYY-MM-DD)',
        dateFormatLong: 'Format Panjang (DD MMMM YYYY)',

        scannerSettings: 'Konfigurasi Scanner QR Kamera',
        scannerSettingsDesc: 'Atur feedback audio, kamera bawaan, dan alur pemindaian cepat.',
        scannerSound: 'Efek Suara Beep Scanner',
        scannerSoundDesc: 'Bunyikan nada konfirmasi saat QR Code berhasil dipindai.',
        scannerCamera: 'Pilihan Kamera Default',
        scannerCameraBack: 'Kamera Belakang / Lingkungan (Rekomendasi)',
        scannerCameraFront: 'Kamera Depan / Pengguna',
        scannerAutoOpen: 'Buka Formulir Transaksi Otomatis',
        scannerAutoOpenDesc: 'Langsung buka pop-up mutasi stok tanpa klik tombol tambahan.',

        batchSettings: 'Pengaturan Batch & Masa Kadaluarsa',
        batchSettingsDesc: 'Kelola ambang batas peringatan waktu kedaluwarsa produk gudang.',
        expiryWarningDays: 'Ambang Hari Peringatan Kadaluarsa',
        days7: '7 Hari Sebelum Kadaluarsa',
        days14: '14 Hari Sebelum Kadaluarsa',
        days30: '30 Hari Sebelum Kadaluarsa (Direkomendasikan)',
        days60: '60 Hari Sebelum Kadaluarsa',

        codeStandards: 'Standardisasi Kode & Prefix Gudang',
        codeStandardsDesc: 'Prefix otomatis untuk penomoran SKU produk dan lot batch baru.',
        skuPrefix: 'Prefix SKU Produk Default',
        skuPrefixDesc: 'Awalan otomatis saat menambahkan produk baru (contoh: PRD-)',
        batchPrefix: 'Prefix Batch/Lot Default',
        batchPrefixDesc: 'Awalan otomatis saat membuat batch baru (contoh: LOT-)',

        defaultMinStock: 'Default Ambang Stok Menipis Produk Baru',
        defaultMinStockDesc: 'Nilai awal stok minimal saat membuka formulir tambah produk baru.',
        minStock5: '5 Unit (Standar Toko / Retail)',
        minStock10: '10 Unit (Stok Menengah)',
        minStock20: '20 Unit (Distribusi Cepat)',
        minStock50: '50 Unit (Gudang Besar / Grosir)',

        fifoPolicy: 'Kebijakan Pengeluaran Barang (FIFO)',
        fifoPolicyDesc: 'Rekomendasikan atau prioritaskan batch terlama saat stok keluar.',
        fifoEnforce: 'Rekomendasi Otomatis FIFO (First-In, First-Out)',
        fifoEnforceDesc: 'Prioritaskan batch tertua / paling mendekati kadaluarsa untuk dikeluarkan terlebih dahulu.',

        qrPrintSettings: 'Preferensi Cetak Label QR Kardus & Rak',
        qrPrintDesc: 'Sesuaikan ukuran stiker dan detail informasi pada label cetak QR fisik.',
        qrLabelSize: 'Ukuran Label Cetak QR',
        sizeSmall: 'Kecil 30×20 mm (Stiker Thermal Mini)',
        sizeMedium: 'Sedang 50×30 mm (Standar Kardus/Rak)',
        sizeStandard: 'Besar / Grid A4 (70×50 mm)',
        qrShowInfo: 'Sertakan Detail Produk di Label Cetak',
        qrShowInfoDesc: 'Cetak nama barang, SKU, dan tanggal exp di bawah gambar QR Code.',

        backupTitle: 'Cadangan Database & Arsip Inventaris',
        backupDesc: 'Unduh salinan lengkap data produk, batch, dan riwayat transaksi dalam format file JSON.',
        downloadBackupBtn: 'Unduh Cadangan Data (JSON)',
        clearCacheTitle: 'Pemeliharaan & Pembersihan Cache',
        clearCacheDesc: 'Bersihkan query cache server dan sinkronisasi data ulang jika data terasa lambat.',
        clearCacheBtn: 'Bersihkan Cache Sistem',
        cacheCleared: 'Cache Berhasil Dibersihkan!',
        backupSuccess: 'Cadangan Data Berhasil Diunduh!',

        saveSettings: 'Simpan Pengaturan',
        settingsSaved: 'Pengaturan Disimpan',
        settingsSavedDesc: 'Preferensi sistem Anda berhasil diperbarui.',
        autoSaved: 'Tersimpan otomatis',
        autoSavedNote: 'Semua pengaturan tersimpan secara otomatis',
        changesSaved: 'Perubahan tersimpan',
        autoSaveActive: 'Tersimpan otomatis',

        notifPreferences: 'Preferensi Notifikasi',
        notifPreferencesDesc: 'Pilih peringatan inventaris yang ingin Anda terima secara langsung.',
        notifLowStock: 'Peringatan Stok Kritis',
        notifLowStockDesc: 'Berikan tanda bahaya ketika stok barang berada di bawah ambang minimal.',
        notifMutation: 'Notifikasi Transaksi Mutasi',
        notifMutationDesc: 'Notifikasi pop-up saat operator mencatat stok masuk atau keluar baru.',
        notifSound: 'Suara Efek Scanner / Alert',
        notifSoundDesc: 'Bunyikan nada saat scanner QR berhasil memindai produk.',

        securityTitle: 'Keamanan Akun & Sistem',
        securityDesc: 'Lindungi akses akun dan kelola batas sesi aktif Anda.',
        sessionTimeout: 'Durasi Batas Waktu Sesi (Timeout)',
        timeout30: '30 Menit Tidak Aktif',
        timeout60: '1 Jam Tidak Aktif',
        timeout120: '2 Jam Tidak Aktif (Direkomendasikan)',
        timeout480: '8 Jam (Sepanjang Jam Kerja)',
        twoFactor: 'Autentikasi Dua Faktor (2FA)',
        twoFactorDesc: 'Minta kode verifikasi tambahan saat login dari perangkat asing.',
        changePwAlert: 'Untuk mengganti password akun Anda, silakan kunjungi menu Profil Saya > Tab Ubah Password.',

        aboutTitle: 'Tentang Sistem Inventaris',
        aboutDesc: 'Spesifikasi dan metadata sistem manajemen barang gudang.',
        appNameField: 'Nama Aplikasi',
        appVersionField: 'Versi Rilis',
        backendEngineField: 'Backend Engine',
        frontendStackField: 'Frontend Stack',
        dbDriverField: 'Database Driver',
        apiStatusField: 'Status Layanan API',
        apiStatusNormal: 'Normal / Aktif',

        // Profile Page
        profileTitle: 'Profil Saya',
        profileSubtitle: 'Kelola informasi akun dan keamanan Anda di sistem Manajemen Barang.',
        tabAccountInfo: 'Informasi Akun',
        tabChangePassword: 'Ubah Password',
        tabPreferences: 'Preferensi',
        personalInfo: 'Informasi Pribadi',
        personalInfoDesc: 'Data ini akan digunakan untuk identifikasi akun Anda.',
        fullName: 'Nama Lengkap',
        email: 'Email',
        role: 'Role',
        joinedDate: 'Tanggal Bergabung',
        joinedSince: 'Bergabung sejak',
        accountStats: 'Statistik Akun',
        lastLogin: 'Login Terakhir',
        totalLogins: 'Total Login',
        timesUnit: 'kali',
        profilePhoto: 'Foto Profil',
        profilePhotoDesc: 'Upload foto profil dengan format JPG, PNG atau WEBP. Maksimal 2MB.',
        changePhoto: 'Ubah Foto',
        removePhoto: 'Hapus',
        securityCallout: 'Untuk keamanan akun, pastikan Anda selalu menggunakan password yang kuat dan tidak membagikannya kepada siapapun.',
        saveChanges: 'Simpan Perubahan',
        profileSaved: 'Berhasil Disimpan',
        profileSavedDesc: 'Informasi profil Anda berhasil diperbarui.',

        passwordTitle: 'Keamanan Kata Sandi',
        passwordDesc: 'Perbarui kata sandi akun Anda secara berkala untuk menjaga keamanan sistem.',
        currentPassword: 'Password Saat Ini',
        newPassword: 'Password Baru',
        confirmNewPassword: 'Konfirmasi Password Baru',
        passwordRules: 'Ketentuan Password:',
        ruleMin8: 'Minimal 8 karakter',
        ruleMix: 'Gunakan kombinasi huruf kapital, angka, atau simbol',
        updatePasswordBtn: 'Ubah Password',
        passwordMismatch: 'Password Tidak Cocok',
        passwordMismatchDesc: 'Konfirmasi password baru tidak sesuai.',
        passwordUpdated: 'Password Diperbarui',
        passwordUpdatedDesc: 'Password akun Anda berhasil diganti.',

        prefTitle: 'Preferensi Akun',
        prefDesc: 'Sesuaikan cara Anda menerima notifikasi dan format alur kerja akun.',
        prefLowStockEmail: 'Notifikasi Email Stok Kritis',
        prefLowStockEmailDesc: 'Kirim email ringkasan saat ada barang berstatus stok menipis atau habis.',
        prefNewDeviceEmail: 'Peringatan Login Perangkat Baru',
        prefNewDeviceEmailDesc: 'Notifikasi email saat akun diakses dari browser atau IP address baru.',
        prefDailyDigest: 'Email Rekap Transaksi Harian',
        prefDailyDigestDesc: 'Kirim rangkuman otomatis mutasi barang masuk & keluar setiap akhir hari / shift.',
        prefSoundAlert: 'Efek Suara Notifikasi Desktop',
        prefSoundAlertDesc: 'Bunyikan nada saat ada peringatan stok atau notifikasi sistem baru.',
        prefConfirmTx: 'Mode Konfirmasi Transaksi Stok',
        prefConfirmTxDesc: 'Minta konfirmasi dialog sebelum menyimpan mutasi barang masuk/keluar untuk mencegah salah ketik.',
        prefConfirmTxActive: 'Mode Aman (Tampilkan Dialog Konfirmasi)',
        prefConfirmTxQuick: 'Mode Cepat (Langsung Simpan Tanpa Dialog)',
        prefTimezone: 'Zona Waktu',
        prefDateFormat: 'Format Tampilan Tanggal',
        prefDateFormatId: 'DD/MM/YYYY (Standar Indonesia)',
        prefDateFormatIso: 'YYYY-MM-DD (Standar ISO)',
        prefDateFormatLong: 'DD MMMM YYYY (Format Panjang)',
        savePrefBtn: 'Simpan Preferensi',
        prefSaved: 'Preferensi Disimpan',
        prefSavedDesc: 'Preferensi akun Anda berhasil diperbarui.',

        // Dashboard
        totalProductsStat: 'Total Produk',
        totalStockStat: 'Total Stok',
        activeCategoriesStat: 'Kategori Aktif',
        lowStockStat: 'Stok Menipis',
        outOfStockStat: 'Stok Habis',
        stockByCategory: 'Stok per Kategori',
        allCategoriesFilter: 'Semua Kategori',
        stockMovement: 'Stok Masuk & Keluar',
        days7: '7 Hari Terakhir',
        days30: '30 Hari Terakhir',
        incomingStock: 'Stok Masuk',
        outgoingStock: 'Stok Keluar',
        todayIn: 'Masuk Hari Ini',
        todayOut: 'Keluar Hari Ini',
        recentActivities: 'Aktivitas Terbaru',
        allStockHealthy: 'Semua Stok Barang Aman',
        allStockHealthyDesc: 'Tidak ada produk yang berada di bawah stok minimal saat ini.',
        criticalAlertBannerTitle: 'Perhatian: Terdapat Stok Kritis!',
        criticalAlertBannerDesc: 'Ada barang yang menipis atau habis. Segera lakukan stok masuk.',
        restockAction: 'Lakukan Stok Masuk',
        units: 'unit',
        items: 'item',

        // Profile & Preferences
        profileTitle: 'Profil Saya',
        profileSubtitle: 'Kelola informasi identitas akun, keamanan, dan preferensi kerja sistem.',
        joinedSince: 'Bergabung sejak',
        accountStats: 'Statistik Akun',
        lastLogin: 'Login Terakhir',
        totalLogins: 'Total Login',
        timesUnit: 'kali',
        tabAccountInfo: 'Informasi Akun',
        tabChangePassword: 'Ubah Password',
        tabPreferences: 'Preferensi',
        personalInfo: 'Informasi Pribadi',
        personalInfoDesc: 'Perbarui detail data pribadi dan alamat email kontak Anda.',
        fullName: 'Nama Lengkap',
        email: 'Alamat Email',
        role: 'Peran / Role',
        joinedDate: 'Tanggal Bergabung',
        profilePhoto: 'Foto Profil',
        profilePhotoDesc: 'Gunakan gambar rasio 1:1 format PNG, JPG, atau WEBP maks 2MB.',
        changePhoto: 'Ganti Foto',
        removePhoto: 'Hapus Foto',
        securityCallout: 'Keamanan: Alamat email digunakan sebagai kredensial otentikasi login serta penerima notifikasi resmi dari sistem inventaris.',
        profileSaved: 'Profil Berhasil Disimpan',
        profileSavedDesc: 'Perubahan profil Anda telah berhasil diperbarui.',
        passwordTitle: 'Keamanan Password',
        passwordDesc: 'Pastikan kata sandi Anda kuat dan tidak digunakan di aplikasi lain.',
        currentPassword: 'Password Saat Ini',
        newPassword: 'Password Baru',
        confirmNewPassword: 'Konfirmasi Password Baru',
        passwordRules: 'Ketentuan Password:',
        ruleMin8: 'Minimal 8 karakter',
        ruleMix: 'Kombinasi huruf besar, huruf kecil, dan angka',
        updatePasswordBtn: 'Perbarui Password',
        passwordMismatch: 'Password Tidak Cocok',
        passwordMismatchDesc: 'Konfirmasi password baru tidak sama dengan password baru.',
        passwordUpdated: 'Password Berhasil Diperbarui',
        passwordUpdatedDesc: 'Silakan gunakan password baru Anda saat login berikutnya.',

        // Preferensi Akun (Point 2 - 6)
        prefTitle: 'Preferensi & Kustomisasi Akun',
        prefDesc: 'Atur alur notifikasi email, mode konfirmasi transaksi, dan format waktu kerja Anda.',
        prefNotifSection: 'Notifikasi & Peringatan',
        prefNotifSectionDesc: 'Kelola frekuensi pemberitahuan dan feedback suara dari sistem inventaris.',
        prefLowStockEmail: 'Peringatan Email Stok Kritis',
        prefLowStockEmailDesc: 'Kirim notifikasi email otomatis saat ada barang yang menipis di bawah batas minimal.',
        prefNewDeviceEmail: 'Notifikasi Login Perangkat Baru',
        prefNewDeviceEmailDesc: 'Dapatkan pemberitahuan email pengamanan setiap kali ada sesi login baru.',
        prefDailyDigest: 'Email Rekap Ringkasan Harian (Daily Digest)',
        prefDailyDigestDesc: 'Kirim rangkuman otomatis mutasi stok masuk dan keluar ke email pada akhir hari kerja.',
        prefSoundAlert: 'Efek Suara Notifikasi (Audio Feedback)',
        prefSoundAlertDesc: 'Bunyikan nada chime saat ada notifikasi penting atau peringatan stok kritis.',
        testSoundBtn: 'Uji Suara',
        soundTesting: 'Memainkan Suara...',

        prefTxSection: 'Alur Konfirmasi Transaksi Stok',
        prefTxSectionDesc: 'Pilih tingkat keamanan atau kecepatan saat memproses stok masuk dan keluar.',
        prefConfirmTx: 'Mode Konfirmasi Transaksi Stok',
        prefConfirmTxSafe: 'Mode Aman (Direkomendasikan)',
        prefConfirmTxSafeDesc: 'Munculkan dialog konfirmasi SweetAlert sebelum transaksi disimpan untuk mencegah salah input.',
        prefConfirmTxQuick: 'Mode Cepat (Instan)',
        prefConfirmTxQuickDesc: 'Langsung simpan mutasi stok tanpa jendela dialog tambahan, cocok untuk operator berpengalaman.',

        prefTimeSection: 'Format Waktu & Tampilan Tanggal',
        prefTimeSectionDesc: 'Pilih format penanggalan yang paling nyaman untuk laporan dan profil.',
        prefTimezone: 'Zona Waktu Kerja',
        prefDateFormat: 'Format Tampilan Tanggal Akun',
        prefDateFormatDesc: 'Standar penulisan tanggal di tabel riwayat dan halaman akun Anda.',
        prefDateFormatId: 'DD/MM/YYYY (Standar Indonesia, misal: 08/10/2026)',
        prefDateFormatIso: 'YYYY-MM-DD (Standar ISO, misal: 2026-10-08)',
        prefDateFormatLong: 'DD MMMM YYYY (Format Panjang, misal: 08 Oktober 2026)',
        previewDateLabel: 'Contoh Pratinjau:',

        savePrefBtn: 'Simpan Preferensi',
        prefSaved: 'Preferensi Berhasil Disimpan',
        prefSavedDesc: 'Pengaturan preferensi akun Anda telah disinkronkan ke server dan browser.',
    },
    en: {
        // Nav & Common
        appName: 'Inventory Management',
        appSubtitle: 'Warehouse System',
        home: 'Home',
        dashboard: 'Dashboard',
        products: 'Products',
        categories: 'Categories',
        suppliers: 'Suppliers',
        stockInOut: 'Stock In / Out',
        batch: 'Inventory Batches',
        reports: 'Data Reports',
        logout: 'Logout',
        logoutConfirmTitle: 'Logout Confirmation',
        logoutConfirmText: 'You will be logged out of the inventory system.',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving...',
        saved: 'Saved',
        delete: 'Delete',
        edit: 'Edit',
        actions: 'Actions',
        success: 'Success',
        error: 'Error',
        warning: 'Warning',
        searchPlaceholder: 'Search products, categories, or SKU...',
        searchNav: 'Search...',

        // Header
        notifications: 'Notifications',
        inventoryNotifications: 'Inventory Notifications',
        markAsRead: 'Mark as read',
        noNotifications: 'No notifications at this time.',
        toggleTheme: 'Toggle Theme',
        myProfile: 'My Profile',
        settings: 'Settings',

        // Settings Page
        settingsTitle: 'Settings',
        settingsSubtitle: 'Manage system preferences and configurations to your needs.',
        tabAppearance: 'Appearance',
        tabAppearanceSub: 'Theme and interface look',
        tabWarehouse: 'Warehouse & Scanner',
        tabWarehouseSub: 'QR scanner, batch, and warehouse codes',
        tabNotifications: 'Notifications',
        tabNotificationsSub: 'System notification settings',
        tabSecurity: 'Security',
        tabSecuritySub: 'Account password & security',
        tabDataManagement: 'Data Management & Backup',
        tabDataManagementSub: 'Backup database and purge system cache',
        tabAbout: 'About System',
        tabAboutSub: 'Version and app information',

        sectionAppearance: 'Appearance',
        sectionAppearanceDesc: 'Customize app theme and appearance according to your preferences.',
        labelTheme: 'Theme',
        themeLight: 'Light',
        themeLightDesc: 'Light interface',
        themeDark: 'Dark',
        themeDarkDesc: 'Dark interface',
        themeSystem: 'System',
        themeSystemDesc: 'Follows system',
        darkModeActive: 'Dark Mode Active',
        lightModeActive: 'Light Mode Active',
        darkPreviewDesc: 'Easier on the eyes in low light conditions.',
        lightPreviewDesc: 'Clean high-contrast look for bright environments.',

        sectionLanguage: 'Language & Localization',
        sectionLanguageDesc: 'Set application language and data formats.',
        labelLanguage: 'Language',
        langIndonesian: 'Bahasa Indonesia',
        langEnglish: 'English (US)',

        sectionOther: 'Other Settings',
        sectionOtherDesc: 'Adjust additional system preferences.',
        toggleAutoRefresh: 'Dashboard Auto Refresh',
        toggleAutoRefreshDesc: 'Periodic automatic data update',
        toggleShowStock: 'Show stock numbers',
        toggleShowStockDesc: 'Display quantity on product cards',
        refreshInterval: 'Auto-Refresh Interval',
        interval1m: '1 Minute (Fast Moving)',
        interval3m: '3 Minutes',
        interval5m: '5 Minutes (Standard)',
        interval10m: '10 Minutes',
        autoRefreshActiveBadge: 'Auto-Refresh Active',
        autoRefreshOffBadge: 'Auto-Refresh Off',
        lastUpdatedLabel: 'Last updated',
        refreshNowBtn: 'Refresh Now',
        refreshingStatus: 'Refreshing data...',
        stockHidden: 'Hidden',

        displayPreferences: 'Data & Table Display Formats',
        displayPreferencesDesc: 'Adjust row density, default data sorting, and table rows per page.',
        paginationLimit: 'Table Rows Per Page',
        rows10: '10 Rows per Page',
        rows25: '25 Rows per Page',
        rows50: '50 Rows per Page',
        rows100: '100 Rows per Page',
        tableDensity: 'Table Row Density',
        densityComfortable: 'Comfortable (Standard)',
        densityCompact: 'Compact (Dense View)',
        defaultSort: 'Default Table Sort Order',
        sortNewest: 'Newest Added',
        sortLowestStock: 'Lowest Stock First (Restock Priority)',
        sortHighestStock: 'Highest Stock First',
        sortNameAsc: 'Product Name (A - Z)',
        dateFormat: 'Transaction Date Format',
        dateFormatId: 'Indonesian Standard (DD/MM/YYYY)',
        dateFormatIso: 'ISO / Logistics Standard (YYYY-MM-DD)',
        dateFormatLong: 'Long Format (DD MMMM YYYY)',

        scannerSettings: 'QR Camera Scanner Configuration',
        scannerSettingsDesc: 'Configure audio feedback, default camera lens, and quick scan flow.',
        scannerSound: 'Scanner Beep Sound Effect',
        scannerSoundDesc: 'Play confirmation tone when QR Code is successfully scanned.',
        scannerCamera: 'Default Camera Lens',
        scannerCameraBack: 'Rear / Environment Camera (Recommended)',
        scannerCameraFront: 'Front / User Camera',
        scannerAutoOpen: 'Auto-Open Transaction Form',
        scannerAutoOpenDesc: 'Directly open stock transaction modal without extra clicks.',

        batchSettings: 'Batch & Expiry Date Settings',
        batchSettingsDesc: 'Manage inventory expiration warning threshold days.',
        expiryWarningDays: 'Batch Expiry Warning Threshold',
        days7: '7 Days Before Expiry',
        days14: '14 Days Before Expiry',
        days30: '30 Days Before Expiry (Recommended)',
        days60: '60 Days Before Expiry',

        codeStandards: 'Code Standards & Warehouse Prefix',
        codeStandardsDesc: 'Automatic prefix formatting for product SKUs and new batch lots.',
        skuPrefix: 'Default Product SKU Prefix',
        skuPrefixDesc: 'Automatic prefix when creating new products (e.g. PRD-)',
        batchPrefix: 'Default Batch/Lot Prefix',
        batchPrefixDesc: 'Automatic prefix when creating new batch lots (e.g. LOT-)',

        defaultMinStock: 'Default Min Stock for New Products',
        defaultMinStockDesc: 'Initial minimum stock threshold when creating new products.',
        minStock5: '5 Units (Standard Retail)',
        minStock10: '10 Units (Medium Stock)',
        minStock20: '20 Units (Fast Distribution)',
        minStock50: '50 Units (Wholesale / Large)',

        fifoPolicy: 'Outbound Stock Policy (FIFO)',
        fifoPolicyDesc: 'Recommend or prioritize oldest expiring batches during stock-out.',
        fifoEnforce: 'Automatic FIFO Recommendation (First-In, First-Out)',
        fifoEnforceDesc: 'Prioritize oldest or earliest expiring batch for stock reduction.',

        qrPrintSettings: 'QR Code Label Printing Settings',
        qrPrintDesc: 'Customize sticker paper size and details printed on physical QR labels.',
        qrLabelSize: 'QR Print Label Size',
        sizeSmall: 'Small 30×20 mm (Mini Thermal)',
        sizeMedium: 'Medium 50×30 mm (Standard Box/Shelf)',
        sizeStandard: 'Large / A4 Grid (70×50 mm)',
        qrShowInfo: 'Include Product Details on Printed Label',
        qrShowInfoDesc: 'Print product name, SKU, and exp date below QR image.',

        backupTitle: 'Database Backup & Inventory Archive',
        backupDesc: 'Download a full snapshot of all products, batches, and transactions in JSON format.',
        downloadBackupBtn: 'Download Data Backup (JSON)',
        clearCacheTitle: 'Cache Maintenance & Cleanup',
        clearCacheDesc: 'Flush server query cache and resynchronize local state if data lags.',
        clearCacheBtn: 'Clear System Cache',
        cacheCleared: 'System Cache Cleared Successfully!',
        backupSuccess: 'Backup Snapshot Downloaded Successfully!',

        saveSettings: 'Save Settings',
        settingsSaved: 'Settings Saved',
        settingsSavedDesc: 'Your system preferences have been updated successfully.',
        autoSaved: 'Auto-saved',
        autoSavedNote: 'All settings are saved automatically',
        changesSaved: 'Changes saved',
        autoSaveActive: 'Auto-save active',

        notifPreferences: 'Notification Preferences',
        notifPreferencesDesc: 'Choose which inventory alerts you want to receive directly.',
        notifLowStock: 'Critical Stock Alert',
        notifLowStockDesc: 'Send warning when item stock falls below minimum threshold.',
        notifMutation: 'Mutation Transaction Alert',
        notifMutationDesc: 'Pop-up alert when operators record new incoming or outgoing stock.',
        notifSound: 'Scanner Sound / Alert',
        notifSoundDesc: 'Play sound effect when QR scanner successfully reads products.',

        securityTitle: 'Account & System Security',
        securityDesc: 'Protect your account access and manage active session limits.',
        sessionTimeout: 'Session Timeout Duration',
        timeout30: '30 Minutes Inactive',
        timeout60: '1 Hour Inactive',
        timeout120: '2 Hours Inactive (Recommended)',
        timeout480: '8 Hours (Full Workday)',
        twoFactor: 'Two-Factor Authentication (2FA)',
        twoFactorDesc: 'Require additional verification code when signing in from new devices.',
        changePwAlert: 'To update your account password, please visit My Profile > Change Password Tab.',

        aboutTitle: 'About Inventory System',
        aboutDesc: 'Specifications and metadata of the warehouse management platform.',
        appNameField: 'Application Name',
        appVersionField: 'Release Version',
        backendEngineField: 'Backend Engine',
        frontendStackField: 'Frontend Stack',
        dbDriverField: 'Database Driver',
        apiStatusField: 'API Service Status',
        apiStatusNormal: 'Normal / Operational',

        // Profile Page
        profileTitle: 'My Profile',
        profileSubtitle: 'Manage your account information and security in the Inventory Management system.',
        tabAccountInfo: 'Account Info',
        tabChangePassword: 'Change Password',
        tabPreferences: 'Preferences',
        personalInfo: 'Personal Information',
        personalInfoDesc: 'This information is used to identify your account.',
        fullName: 'Full Name',
        email: 'Email',
        role: 'Role',
        joinedDate: 'Joined Date',
        joinedSince: 'Joined since',
        accountStats: 'Account Statistics',
        lastLogin: 'Last Login',
        totalLogins: 'Total Logins',
        timesUnit: 'times',
        profilePhoto: 'Profile Photo',
        profilePhotoDesc: 'Upload profile photo in JPG, PNG or WEBP format. Maximum 2MB.',
        changePhoto: 'Change Photo',
        removePhoto: 'Remove',
        securityCallout: 'For account security, always use a strong password and never share it with anyone.',
        saveChanges: 'Save Changes',
        profileSaved: 'Saved Successfully',
        profileSavedDesc: 'Your profile information has been updated.',

        passwordTitle: 'Password Security',
        passwordDesc: 'Periodically update your account password to maintain system security.',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordRules: 'Password Requirements:',
        ruleMin8: 'At least 8 characters',
        ruleMix: 'Use combination of uppercase letters, numbers, or symbols',
        updatePasswordBtn: 'Update Password',
        passwordMismatch: 'Password Mismatch',
        passwordMismatchDesc: 'New password confirmation does not match.',
        passwordUpdated: 'Password Updated',
        passwordUpdatedDesc: 'Your account password was updated successfully.',

        prefTitle: 'Account Preferences',
        prefDesc: 'Customize how you receive alerts and personal workflow format.',
        prefLowStockEmail: 'Low Stock Email Alerts',
        prefLowStockEmailDesc: 'Send email summary when items become low or out of stock.',
        prefNewDeviceEmail: 'New Device Login Alert',
        prefNewDeviceEmailDesc: 'Email warning when account is accessed from a new browser or IP.',
        prefDailyDigest: 'Daily Transaction Email Digest',
        prefDailyDigestDesc: 'Send automatic daily summary of incoming and outgoing stock transactions.',
        prefSoundAlert: 'Desktop Notification Sound Alert',
        prefSoundAlertDesc: 'Play audio chime when new stock alerts or system notifications arrive.',
        prefConfirmTx: 'Stock Transaction Confirmation Mode',
        prefConfirmTxDesc: 'Prompt confirmation dialog before saving stock in/out to prevent typos.',
        prefConfirmTxActive: 'Safe Mode (Show Confirmation Dialog)',
        prefConfirmTxQuick: 'Quick Mode (Save Directly Without Dialog)',
        prefTimezone: 'Time Zone',
        prefDateFormat: 'Date Display Format',
        prefDateFormatId: 'DD/MM/YYYY (Indonesian Standard)',
        prefDateFormatIso: 'YYYY-MM-DD (ISO Standard)',
        prefDateFormatLong: 'DD MMMM YYYY (Long Text Format)',
        savePrefBtn: 'Save Preferences',
        prefSaved: 'Preferences Saved',
        prefSavedDesc: 'Your account preferences have been updated successfully.',

        // Dashboard
        totalProductsStat: 'Total Products',
        totalStockStat: 'Total Stock',
        activeCategoriesStat: 'Active Categories',
        lowStockStat: 'Low Stock',
        outOfStockStat: 'Out of Stock',
        stockByCategory: 'Stock by Category',
        allCategoriesFilter: 'All Categories',
        stockMovement: 'Stock In & Out Movement',
        days7: 'Last 7 Days',
        days30: 'Last 30 Days',
        incomingStock: 'Stock In',
        outgoingStock: 'Stock Out',
        todayIn: 'In Today',
        todayOut: 'Out Today',
        recentActivities: 'Recent Activities',
        allStockHealthy: 'All Stock Levels Normal',
        allStockHealthyDesc: 'No products are currently under minimum stock threshold.',
        criticalAlertBannerTitle: 'Attention: Critical Stock Levels Detected!',
        criticalAlertBannerDesc: 'Some products are running low or out of stock. Please restock soon.',
        restockAction: 'Perform Stock In',
        units: 'units',
        items: 'items',

        // Profile & Preferences
        profileTitle: 'My Profile',
        profileSubtitle: 'Manage account identity, security credentials, and workflow preferences.',
        joinedSince: 'Joined since',
        accountStats: 'Account Statistics',
        lastLogin: 'Last Login',
        totalLogins: 'Total Logins',
        timesUnit: 'times',
        tabAccountInfo: 'Account Info',
        tabChangePassword: 'Change Password',
        tabPreferences: 'Preferences',
        personalInfo: 'Personal Information',
        personalInfoDesc: 'Update your personal details and primary contact email.',
        fullName: 'Full Name',
        email: 'Email Address',
        role: 'Role / Position',
        joinedDate: 'Joined Date',
        profilePhoto: 'Profile Photo',
        profilePhotoDesc: 'Use a 1:1 ratio PNG, JPG, or WEBP image up to 2MB.',
        changePhoto: 'Change Photo',
        removePhoto: 'Remove Photo',
        securityCallout: 'Security note: Your email address is used as authentication credentials and recipient for official system alerts.',
        profileSaved: 'Profile Saved Successfully',
        profileSavedDesc: 'Your profile changes have been successfully updated.',
        passwordTitle: 'Password Security',
        passwordDesc: 'Ensure your password is strong and not reused on other platforms.',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordRules: 'Password Requirements:',
        ruleMin8: 'At least 8 characters',
        ruleMix: 'Combination of uppercase, lowercase letters and numbers',
        updatePasswordBtn: 'Update Password',
        passwordMismatch: 'Passwords Do Not Match',
        passwordMismatchDesc: 'New password confirmation does not match.',
        passwordUpdated: 'Password Updated Successfully',
        passwordUpdatedDesc: 'Please use your new password on your next login session.',

        // User Preferences (Point 2 - 6)
        prefTitle: 'Account Preferences & Customization',
        prefDesc: 'Configure email alerts, transaction confirmation safety, and date formats.',
        prefNotifSection: 'Notifications & Alerts',
        prefNotifSectionDesc: 'Manage alert frequency and desktop audio chime feedback.',
        prefLowStockEmail: 'Critical Stock Email Alert',
        prefLowStockEmailDesc: 'Receive automated email warnings when inventory falls below minimum threshold.',
        prefNewDeviceEmail: 'New Device Login Alert',
        prefNewDeviceEmailDesc: 'Get security notifications whenever a login occurs from a new session.',
        prefDailyDigest: 'Daily Inventory Digest Email',
        prefDailyDigestDesc: 'Send daily end-of-day stock movement summary to your registered email.',
        prefSoundAlert: 'Notification Sound Effect (Audio Chime)',
        prefSoundAlertDesc: 'Play a pleasant audio chime when system alerts or critical events occur.',
        testSoundBtn: 'Test Sound',
        soundTesting: 'Playing Sound...',

        prefTxSection: 'Stock Transaction Workflow',
        prefTxSectionDesc: 'Choose transaction safety level or quick execution speed for inventory mutations.',
        prefConfirmTx: 'Transaction Confirmation Mode',
        prefConfirmTxSafe: 'Safe Mode (Recommended)',
        prefConfirmTxSafeDesc: 'Show SweetAlert prompt before committing stock changes to prevent human errors.',
        prefConfirmTxQuick: 'Quick Mode (Instant)',
        prefConfirmTxQuickDesc: 'Immediately commit stock in/out mutations without confirmation dialogs.',

        prefTimeSection: 'Timezone & Date Display Format',
        prefTimeSectionDesc: 'Select preferred date formatting for activity logs and reports.',
        prefTimezone: 'Operating Timezone',
        prefDateFormat: 'Account Date Display Format',
        prefDateFormatDesc: 'Standard date layout in account overview and transaction logs.',
        prefDateFormatId: 'DD/MM/YYYY (Indonesian Standard, e.g. 08/10/2026)',
        prefDateFormatIso: 'YYYY-MM-DD (ISO Standard, e.g. 2026-10-08)',
        prefDateFormatLong: 'DD MMMM YYYY (Long Format, e.g. 08 October 2026)',
        previewDateLabel: 'Preview Sample:',

        savePrefBtn: 'Save Preferences',
        prefSaved: 'Preferences Saved Successfully',
        prefSavedDesc: 'Your account preferences have been synchronized to server and browser.',
    }
};

export function LanguageProvider({ children }) {
    const getInitialLanguage = () => {
        const savedLang = localStorage.getItem('appLanguage');
        if (savedLang === 'en' || savedLang === 'id') return savedLang;
        const savedSettings = localStorage.getItem('appSettings');
        if (savedSettings) {
            try {
                const parsed = JSON.parse(savedSettings);
                if (parsed.language === 'en' || parsed.language === 'id') return parsed.language;
            } catch (e) {}
        }
        return 'id';
    };

    const [language, setLanguageState] = useState(getInitialLanguage);

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
        document.documentElement.lang = language;
    }, [language]);

    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('appLanguage', lang);
        // Also update settings in localStorage
        const savedSettings = localStorage.getItem('appSettings');
        let currentSettings = {};
        if (savedSettings) {
            try {
                currentSettings = JSON.parse(savedSettings);
            } catch (e) {}
        }
        currentSettings.language = lang;
        localStorage.setItem('appSettings', JSON.stringify(currentSettings));
        window.dispatchEvent(new Event('language-changed'));
    };

    const t = (key, fallback = '') => {
        const langObj = translations[language] || translations.id;
        return langObj[key] ?? translations.id[key] ?? fallback ?? key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
